version: "3"
services:
  node_server:
    build:
      context: ./node_backend
    entrypoint: zsh -c "yarn start && echo Backend running..."
    volumes:
      - ../node_backend:/app
      - /app/docker
      - ./node_backend/container_startup.sh:/app/docker/node_backend/container_startup.sh
    links:
      - "mongodb"
    ports:
      - "28191:443"
      - "25585:25585"
    stdin_open: true
    tty: true

  mongodb:
    build:
      context: ./mongodb
    entrypoint: /app/docker/mongodb/container_startup.sh
    volumes:
      - ./mongodb/container_startup.sh:/app/docker/mongodb/container_startup.sh
      - ../mongo_db:/data/db/
      - ../mongo_db/log/:/var/log/
    ports:
      - "27017"
    stdin_open: true
    tty: true
